#!/usr/bin/env python3
"""Interactive .env setup for Crypto Alpha Scanner."""

from getpass import getpass
from pathlib import Path

ENV_PATH = Path(".env")

DEFAULTS = {
    "AI_PROVIDER": "openrouter",
    "AI_MODEL": "qwen/qwen3-coder:free",
    "OPENROUTER_BASE_URL": "https://openrouter.ai/api/v1",
    "GROQ_BASE_URL": "https://api.groq.com/openai/v1",
    "GITHUB_MODELS_BASE_URL": "https://models.github.ai/inference",
    "LOCAL_AI_API_KEY": "local",
    "AUTO_TRADE": "false",
    "WATCH_MODE": "false",
    "SCAN_INTERVAL_MINUTES": "15",
    "TRADING_MODE": "paper",
    "TRADING_EXCHANGE": "paper",
    "LIVE_TRADING": "false",
    "PAPER_TRADES_PATH": "data/paper_trades.jsonl",
    "POSITION_STATE_PATH": "data/positions.json",
    "TRADING_QUOTE_SYMBOL": "USDT",
    "TRADINGVIEW_WEBHOOK_HOST": "127.0.0.1",
    "TRADINGVIEW_WEBHOOK_PORT": "8787",
    "BINANCE_TESTNET": "false",
    "REDDIT_USER_AGENT": "CryptoAlphaScanner/1.0",
}

FIELDS = [
    ("AI_PROVIDER", "AI provider (openai/openrouter/groq/github/local)", False),
    ("AI_MODEL", "AI model", False),
    ("OPENAI_API_KEY", "OpenAI API key", True),
    ("OPENROUTER_API_KEY", "OpenRouter API key", True),
    ("GROQ_API_KEY", "Groq API key", True),
    ("GITHUB_TOKEN", "GitHub token", True),
    ("LOCAL_AI_BASE_URL", "Local OpenAI-compatible base URL", False),
    ("TELEGRAM_BOT_TOKEN", "Telegram bot token", True),
    ("TELEGRAM_CHAT_ID", "Telegram chat id", False),
    ("TRADING_MODE", "Trading mode (paper/live)", False),
    ("TRADING_EXCHANGE", "Trading exchange (paper/binance)", False),
    ("LIVE_TRADING", "Enable live trading? true/false", False),
    ("BINANCE_API_KEY", "Binance API key", True),
    ("BINANCE_API_SECRET", "Binance API secret", True),
    ("BINANCE_TESTNET", "Use Binance testnet? true/false", False),
    ("TRADINGVIEW_WEBHOOK_SECRET", "TradingView webhook secret", True),
    ("ETHERSCAN_API_KEY", "Etherscan API key", True),
    ("WHALE_ALERT_API_KEY", "Whale Alert API key", True),
]


def read_env() -> dict:
    values = dict(DEFAULTS)
    if not ENV_PATH.exists():
        return values
    for raw in ENV_PATH.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def ask(key: str, label: str, secret: bool, current: str) -> str:
    shown = "***" if secret and current else current
    prompt = f"{label} [{shown}]: " if current else f"{label}: "
    value = getpass(prompt) if secret else input(prompt)
    return value.strip() or current


def write_env(values: dict) -> None:
    ordered = list(DEFAULTS.keys()) + [k for k, _, _ in FIELDS if k not in DEFAULTS]
    lines = ["# Generated by python main.py --setup"]
    for key in ordered:
        lines.append(f'{key}="{values.get(key, "")}"')
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ENV_PATH.chmod(0o600)


def main() -> None:
    print("Crypto Alpha Scanner setup")
    print("Bos birakirsan mevcut/deger varsayilan kalir. Secret degerler ekrana yazilmaz.")
    values = read_env()
    for key, label, secret in FIELDS:
        values[key] = ask(key, label, secret, values.get(key, ""))
    write_env(values)
    print(f".env guncellendi: {ENV_PATH.resolve()}")
    print("Canli Binance icin withdrawal kapali ve IP restriction acik API key kullan.")


if __name__ == "__main__":
    main()
